# Generated by Django 2.2.9 on 2020-02-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Birthday')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(default='', max_length=300)),
                ('postal_code', models.CharField(default='', max_length=300)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Enter phone number', max_length=31)),
                ('profile_photo', models.ImageField(upload_to=None, verbose_name='user_photo')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
