# Generated by Django 2.2.9 on 2020-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200206_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='media_house', verbose_name='Profile Photo'),
        ),
    ]
